[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"

[compat]
DiffEqCallbacks = "4.12.0"
JLD2 = "0.6.3"
ModelingToolkit = "11.9.0"
OrdinaryDiffEq = "6.108.0"
SteadyStateDiffEq = "2.9.0"
